### ISSUE TITLE
Crash when receiving a new specific notification

### ISSUE THREAD

**Issue by david-barbion** [david-barbion/linconnect-server#3]
```
Accepted connection from  ('CC:C3:EA:BC:66:28', 1)
Starting bluetooth client thread
Exception in thread Thread-25:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "linconnect_server.py", line 189, in run
    header_data_json = base64.b64decode(self.get_data())
  File "/usr/lib/python2.7/base64.py", line 76, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding

should exit
```

**Comment by david-barbion** [comment]
Fix applied on the function that reads data from the bluetooth socket: 3a83fb65a14146866ee2eaeeac31e3b5cf9c7420
