### ISSUE TITLE
Crash when enable_avahi not present in config

### ISSUE THREAD

**Issue by valvin1** [david-barbion/linconnect-server#4]
Loading conf.ini
Notification switched on
Traceback (most recent call last):
  File "linconnect_server.py", line 403, in <module>
    server.initialize()
  File "linconnect_server.py", line 318, in initialize
    if parser.getboolean('connection', 'enable_avahi') == 1:
  File "/usr/lib/python2.7/ConfigParser.py", line 368, in getboolean
    v = self.get(section, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'enable_avahi' in section: 'connection'

**Comment by david-barbion** [comment]
Yes, that due to a change in parameter list. For instance, you should manually edit `~/.config/linconnect-server/conf.ini`. In this file, you will find a line containing `enable_bonjour`. Change to `enable_avahi`
